
package com.mycompany.poe;

//Import scanner
import java.util.Scanner;

//(Ali, 2025)
//Import Random Number Generator
import java.util.Random;
      
public class Messages {
    
    Scanner scan = new Scanner(System.in);
    Random random = new Random();     
    
    /*
    Option 1: Send Messages
    
    * User needs to specify how many messages they wish to send.
    * Each message should contain the following information:
        - Unique message ID
            → randomly generated 10-digit number
        - Message number
            → Number to be incremented
            → autogenerated
            → e.g. message1, message2
        - User to specify the recipient
            → Cellphone number rules apply
        - Message length
            → max 250 characters
        - Message Hash
            → first two numbers of message id + : + message number + : + first and last words of message
            → as capital letters
        - Message menu
            → "Message successfully sent"
            → "Press 0 to delete the message"
            → "Message successfully stored"
        - JSON file to store the messages
        - Message receipt
            → message ID
            → Message Hash
            → recipient
            → message
        - Once all messages have been sent: display total number of messages sent.
    */
    
    //Declare private variables:
    private int storedMessageCount;
    private int storedMessageSentCount;
    private String storedMessageID;
    private int storedMessageNumber;
    private String storedRecipient;
    private String storedMessageText;
    private String storedMessageHash;
    
    //Getters & Setters:

    public Scanner getScan() {
        return scan;
    }

    public void setScan(Scanner scan) {
        this.scan = scan;
    }

    public Random getRandom() {
        return random;
    }
    
    public void setRandom(Random random) {
        this.random = random;
    }

    public int getStoredMessageCount() {
        return storedMessageCount;
    }
    
    public void setStoredMessageCount(int storedMessageCount) {
        this.storedMessageCount = storedMessageCount;
    }

    public int getStoredMessageSentCount() {
        return storedMessageSentCount;
    }
    
    public void setStoredMessageSentCount(int storedMessageSentCount) {
        this.storedMessageSentCount = storedMessageSentCount;
    }

    public String getStoredMessageID() {
        return storedMessageID;
    }
    
    public void setStoredMessageID(String storedMessageID) {
        this.storedMessageID = storedMessageID;
    }

    public int getStoredMessageNumber() {
        return storedMessageNumber;
    }
    
    public void setStoredMessageNumber(int storedMessageNumber) {
        this.storedMessageNumber = storedMessageNumber;
    }

    public String getStoredRecipient() {
        return storedRecipient;
    }
    
    public void setStoredRecipient(String storedRecipient) {
        this.storedRecipient = storedRecipient;
    }
    

    public String getStoredMessageText() {
        return storedMessageText;
    }
    
    public void setStoredMessageText(String storedMessageText) {
        this.storedMessageText = storedMessageText;
    }

    public String getStoredMessageHash() {
        return storedMessageHash;
    }
    
    public void setStoredMessageHash(String storedMessageHash) {
        this.storedMessageHash = storedMessageHash;
    }
    
    //Parameter and Validation Methods:
    //Message ID:
    public String checkMessageID() {
        //(Ali, 2025)
        //Declaring message ID
        long generateID = Math.abs(random.nextLong() % 1000000000L);
        //convert it to a string
        String messageID = String.format("%010d", generateID);
        
        return "Message ID generated: " + messageID;
    }
    
    //Message Text Length:
    public String checkMessageText(String messageText) {
        if(messageText.length() <= 250) {
            return "Message ready to send.";
        } else {
            int excessCharacters = messageText.length() - 250;
            return "Message exceeds 250 characters by " + excessCharacters + ". Please reduce the size.";
        }
    }
    
    //Recipient cellphone number:
    public String checkRecipient(String recipient) {
        String regexc = "^(\\+27|0027)[0-9]{3,10}$"; 
        
        if (recipient.matches(regexc)) {
            return "Cellphone number successfully captured.";
        } else {
            return "Invalid cellphone number. Please provide a number starting with +27.";
            }        
    }
    
    //(Geeks for Geeks, 2025)
    //(W3Schools, 2026)
    //Message Hash as an array
    public String checkMessageHash(String messageID, int messageNumber, String messageText) {
        if (messageText == null || messageText.trim().isEmpty()) {
            String messageIDPrefix = messageID.substring(0, 2);
            int messageSentNumber = messageNumber -1;
            return messageIDPrefix + ":" + messageSentNumber + ":";
        }
        
        String[] words = messageText.trim().split("\\s+");
        String firstWord = words.length > 0 ? words[0] : "";
        String lastWord = words.length > 0 ? words[words.length - 1] : "";
        
        //Use this information to build the hash
        String messageIDPrefix = messageID.substring(0, 2);
        int messageSentNumber = messageNumber -1;
        String firstLastWords = (firstWord + lastWord).toUpperCase();
        
        return messageIDPrefix + ":" + messageSentNumber + ":" + firstLastWords;
    }
    
    //Send Message Menu, responses to action selected
    public String messageMenu(String action) {
        
        switch (action) {
            case "1" :
                return "Message successfully sent :)";
            case "0" :
                return "Message deleted successfully.";
            case "3" : 
                return "Message saved successfully.";
            default :
                return "Invalid menu option selected.";
        }
    }
    
      
}
